### ISSUE TITLE
List of breaks

### ISSUE THREAD

**Issue by bast** [coderefinery/2023-03-21-workshop#23]
We have been asked this to simplify organizing coffee breaks. Maybe we can add it to the page or make it clearer in future.

all times in CE(S)T and tentative

Tue:
- 10:05 - 10:15
- 11:10 - 11:20
- 12:05 - 12:10

Wed:
- 09:55 - 10:10
- 11:05 - 11:15
- 11:50 - 12:00

Thu:
- 09:45 - 09:55
- 11:00 - 11:10
- 12:00 - 12:10

Tue:
- 10:00 - 10:10
- 11:05 - 11:15
- around 12:00

Wed:
- 10:00 - 10:10
- 10:55 - 11:05
- 12:00 - 12:10

Thu:
- 09:45 - 09:55
- 10:45 - 11:00
- around 12:00

**Comment by bast** [comment]
I pieced it together from individual lesson schedules. This information is currently hard to gather and find. Not FAIR :-)

**Comment by rkdarst** [comment]
I see the sentiment, but wonder if this is promising more that we can.  Does this provide tangibly more benefit than "10 minutes between xx:50 and xx:10, we can't promise exactly when"?  (perhaps schedules are much more fixed this year)

**Comment by bast** [comment]
I agree. I am also unsure whether we should publish a detailed version since it is likely we will forget to update it in future. Generally we should say that every hour 10 minutes minimum (I am aware that on day 1 we don't follow it).
